name: iOS Build

on:
  workflow_dispatch:  # 手動実行のみ
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ios-build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Clean build
      run: flutter clean
    
    - name: Build iOS Release
      run: flutter build ios --release --no-codesign
    
    - name: Upload iOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-release-build
        path: build/ios/iphoneos/
        retention-days: 7
    
    - name: Build iOS Debug
      run: flutter build ios --debug --no-codesign
    
    - name: Upload iOS debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-debug-build
        path: build/ios/iphoneos/
        retention-days: 7 