name: Xcode Cloud Build

on:
  workflow_dispatch:

jobs:
  xcode-cloud:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
    
    - name: Install dependencies
      run: |
        flutter pub get
        cd ios && pod install && cd ..
    
    - name: Build for Xcode Cloud
      run: |
        flutter build ios --release
        # Xcode Cloud用の署名設定
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/ios/Runner.xcarchive \
          archive 